/**
 * POST /api/auth/teams-token
 *
 * Exchanges a short-lived one-time token (generated by the OAuth callback popup)
 * for a session cookie issued in the Teams iframe context.
 *
 * This is the final step of the Teams SSO handoff:
 *   popup → OAuth → callback generates token → teams-end notifySuccess(token)
 *   → login page receives token → POSTs here → session cookie set on iframe request
 */
import { NextRequest, NextResponse } from "next/server";
import { getIronSession } from "iron-session";
import { sessionOptions } from "@/lib/session";
import type { SessionData } from "@/lib/session";
import { consumeTeamsToken } from "@/lib/teams-tokens";
import { stampLastLogin } from "@/lib/db-store";

export async function POST(request: NextRequest) {
  const body = (await request.json().catch(() => ({}))) as { token?: string };
  const token = body.token?.trim();

  if (!token) {
    return NextResponse.json({ error: "Missing token." }, { status: 400 });
  }

  const data = consumeTeamsToken(token);
  if (!data) {
    return NextResponse.json({ error: "Token expired or already used." }, { status: 401 });
  }

  const response = NextResponse.json({ ok: true });

  const session = await getIronSession<SessionData>(request, response, sessionOptions);
  session.userId    = data.userId;
  session.role      = data.role as SessionData["role"];
  session.firstName = data.firstName;
  session.lastName  = data.lastName;
  await session.save();

  // Record last login timestamp
  stampLastLogin(data.userId).catch(() => {});

  return response;
}
